---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: routers
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: "Gerenciamento CaC dos roteadores do ambiente"
  destinations:
    - namespace: "*"
      server: "*"
      name: "*"
  orphanedResources:
    warn: true
  sourceRepos:
    - "*"

---
apiVersion: v1
kind: Secret
metadata:
  name: router-configs-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/faraujosilva/router-configs.git
  project: router
  username: oauth2
  type: git

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: routers
spec:
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  project: routers
  source:
    repoURL: https://github.com/faraujosilva/router-configs.git
    path: routers
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: router01-setup-app
  namespace: argocd
spec:
  project: routers
  source:
    repoURL: https://github.com/faraujosilva/router-configs.git
    targetRevision: main
    path: routers/router01/setup
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
      - ServerSideApply=false
      - CreateNamespace=true