---
apiVersion: network.argonetops.io/v1alpha1
kind: DeviceConfig
metadata:
  name: router01
  namespace: routers
spec:
  hostname: router01
  ip: 192.168.244.151
  deviceType: cisco_ios
  port: 22
  access: ssh
  username:
    configMapKeyRef:
      name: device-credentials
      key: username
  password:
    configMapKeyRef:
      name: device-credentials
      key: password
